### ISSUE TITLE
Terraform private registry - Sync Tags option 

### ISSUE THREAD

**Issue by githubvikrams** [hashicorp/terraform-docs-common#389]
The documentation in this link "https://www.terraform.io/registry/modules/publish" says that there is a manual option to sync latest tags from Github repository , but not able to find the manage module dropdown in the UI. 

**If your version doesn't appear properly, you may force a sync with GitHub by viewing your module on the registry and clicking "Resync Module" under the "Manage Module" dropdown.**

**Comment by rkoron007** [comment]
Hello @githubvikrams! I know this answer has been a long time coming, and I apologize for that. I just tested this myself, and found the "Resync Module" button while viewing my module in the registry:
![Screenshot 2024-07-16 at 4 14 44 PM](https://github.com/user-attachments/assets/321447a3-9c68-4d9e-97a0-c0bce440992f)
So, I'm going to close this issue because I think the docs match the reality of what you do in this scenario. Thank you so much for opening this issue though!
